### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by rarelygoeshere** [Seedmanc/Booru-Augmentation-Project#10]
I'm using violentmonkey, and I've implemented the script properly, but I notice that the script's not working with the booru despite that. I was wondering if the booru got updated in such a way that makes the script non-functional atm. Of course, I could be doing something wrong, in which case, I'm willing to listen and examine what I did too. Hopefully, this matter can be resolved, and the script will be good to go.

**Comment by Seedmanc** [comment]
The booru.org got ruined with mandatory captcha on every action due to its paranoid owner. Even admins of the boorus can't avoid that. Unfortunately this interferes with the script's work and it's pretty much readonly now.
