### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ProximaNova** [Seedmanc/Booru-Augmentation-Project#3]
You should add Linkify to your script:
view-source:https://arantius.com/misc/greasemonkey/linkify-plus.user.js

**Comment by Seedmanc** [comment]
How do I add a userscript to another other than the blatant copying of contents into mine? Wonder if there are better ways.

Besides, where will it be useful? I recall links are already linkified (eh) on the forums. Where else, comments, sources?

**Comment by ProximaNova** [comment]
I can't imagine any better way than copying; you just have to check that none of the variables and function are the same.

HTTP links work at the forums and comments and not the sources; HTTPS links work nowhere.
