### ISSUE TITLE
Tag wiki

### ISSUE THREAD

**Issue by ProximaNova** [Seedmanc/Booru-Augmentation-Project#4]
The "?" part before the tag was meant to link to a tag wiki but said wiki was only implemented in newer versions; thus, at my the mass editor script I had it link to a Google search of the tag (and was thinking of making the dot part of the question mark link to the tag wiki at Gelbooru or Danbooru). The problem is you removed that part where it was still useful.

Here is one examples:
- http://redpill.booru.org/index.php?page=post&s=view&id=22665

Only a master weeaboo would know what all the current or future tags are or would have to copy and paste them to search at Google or Gelbooru, so to quickly figure out I made it link to Google (and possibly Gelbooru in the future).

**Comment by Seedmanc** [comment]
Good point, I'll return it. You see, I was making this userscript pretty much with the sole purpose of enhancing my koe.booru.org and to help me with mass editing the tags, thus the limited and specific changes to the UI. I should aim the script to the broader range of users, but not being an avid booru visitor it is less obvious for me to see what's needed.

**Comment by Seedmanc** [comment]
Done. 

> making the dot part of the question mark link to the tag wiki at Gelbooru or Danbooru).

Haha what, that's pixelhunting. I suggest you link to a google search of the original tag (without replacing _ with +), this will have the booru wikis in the first results of the search, two birds with one stone.
