### ISSUE TITLE
Tag quantity at alias list

### ISSUE THREAD

**Issue by ProximaNova** [Seedmanc/Booru-Augmentation-Project#5]
How do you get the quantity of a tag? I really wonder how and I don't entirely understand the script your wrote. The point is said numbers could be placed in parenthesis next to tags at http://*.booru.org/index.php?page=alias. I could append the numbers with loops here: https://github.com/ProximaNova/Booru-Augmentation-Project/blob/master/alias-list.user.js

**Comment by Seedmanc** [comment]
Quantity is saved in the localStorage database (BAPtags) along with the tags themselves (tag is the key, value is the quantity). I will incorporate the numbers when I assimilate that user.js.
