### ISSUE TITLE
Rawgit.com has shut down

### ISSUE THREAD

**Issue by tbw0220** [Seedmanc/Booru-Augmentation-Project#9]
Hi, use your script pretty regularly for my booru on booru.org. Recently I've been having issues loading a specific page from rawgit.com, https://rawgit.com/Seedmanc/Booru-Augmentation-Project/master/js/postPage.js. Sometimes clearing my browser's cookies would work, but this time it hasn't been working.

If you go to their main page, https://rawgit.com/, you'll see that the project has been shut down and the content hosted there is no longer reliable.

The solution to this bug would be to host the postPage.js file somewhere else. I believe github.com now lets you do this from your own repositiory (though I have not looked too deep into this myself). I'm hoping you'll be able to help and host it through this repo, but I'm not opposed to making my own repo just to host this page if it lets me keep using the userscript.

**Comment by Seedmanc** [comment]
This should have been fixed in #8, are you sure you have updated to 1.1.2?

**Comment by tbw0220** [comment]
Sorry, I was still on v1.1.1. Hadn't seen that there was a newer version.
